# AWS Resource Manager Configuration

# AWS region to scan for resources
region: "us-east-1"

# Output settings
output:
  # Directory to save JSON reports
  report_dir: "reports"
  # Report file name format (will be appended with timestamp)
  report_prefix: "aws_resource_report"

# Default tags to apply to all resources
tags:
  organization: "flatstone services"
  business_unit: "marketing"
  environment: "dev"

# Solutions configuration
solutions:
  # Static website solution
  static_website:
    # Template location
    template_path: "iac/static_website/template.yaml"
    # Directory for storing deployed templates
    deployed_dir: "iac/deployed"
    # Content directory for static website files
    content_dir: "iac/static_website/content"
    # Default parameters for CloudFormation deployment
    parameters:
      BucketNamePrefix: "flatstone-solutions"
      OriginShieldRegion: "us-east-1"
  
  # Messaging solution for SMS and email contact forms
  messaging:
    # Template location
    template_path: "iac/messaging/template.yaml"
    # Directory for storing deployed templates
    deployed_dir: "iac/deployed"
    # Default parameters for CloudFormation deployment
    parameters:
      # No additional parameters needed as they are pulled from the messaging section
  
  # Streaming media solution for live streaming and video on demand
  streaming_media:
    # Template location
    template_path: "iac/streaming_media/template.yaml"
    # Directory for storing deployed templates
    deployed_dir: "iac/deployed"
    # Default parameters for CloudFormation deployment
    parameters:
      LiveInputType: "RTMP_PUSH"
      LiveInputWhitelistCidr: "173.72.178.22/32"

# S3 settings
s3:
  # S3 bucket for uploading static website content
  bucket: "flatstone-solutions-us-east-1"

# Messaging settings for SMS and email notifications
messaging:
  # Email notification settings
  email:
    # Destination email address for contact form submissions
    destination: "jesse.bacon@flatstoneservices.com"
  
  # SMS notification settings
  sms:
    # Destination phone number for SMS messages (must be in E.164 format)
    destination: "+17033986004"
    # Country code for SMS messages (ISO 3166-1 alpha-2 code)
    country: "US"
    # Originator ID for SMS messages (required by AWS End User Messaging)
    originator_id: "JesseBacon"

