# AWS Infrastructure Report Configuration

# AWS region to scan for resources
region: us-east-1

# Output settings
output:
  # Directory to save JSON reports
  report_dir: "reports"
  # Report file name format (will be appended with timestamp)
  report_prefix: "aws_infra_report"

# S3 settings
s3:
  # S3 bucket for uploading static website content
  bucket: "your-s3-bucket-name"
