---
# Simplified CloudFormation template for static website
# Only includes S3 bucket, CloudFront distribution, and bucket policy
Parameters:
  BucketNamePrefix:
    Type: String
    Description: Prefix for S3 bucket name
    Default: "flatstone-solutions"

  OriginShieldRegion:
    Type: String
    Description: AWS region for CloudFront Origin Shield
    Default: "us-east-2"
    
  OrganizationTag:
    Type: String
    Description: Organization tag for resources
    Default: "flatstone services"
    
  BusinessUnitTag:
    Type: String
    Description: Business unit tag for resources
    Default: "marketing"
    
  EnvironmentTag:
    Type: String
    Description: Environment tag for resources
    Default: "dev"

Resources:
  # S3 Bucket for static website content
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${AWS::Region}"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Organization
          Value: !Ref OrganizationTag
        - Key: BusinessUnit
          Value: !Ref BusinessUnitTag
        - Key: Environment
          Value: !Ref EnvironmentTag

  # S3 Bucket Policy for CloudFront access
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${StaticWebsiteBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # CloudFront Origin Access Control
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${StaticWebsiteBucket}.s3.${AWS::Region}.amazonaws.com"
            Id: S3Origin
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig: {}
            OriginShield:
              Enabled: true
              OriginShieldRegion: !Ref OriginShieldRegion
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # Using managed cache policy: CachingOptimized
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Organization
          Value: !Ref OrganizationTag
        - Key: BusinessUnit
          Value: !Ref BusinessUnitTag
        - Key: Environment
          Value: !Ref EnvironmentTag

Outputs:
  CloudFrontDistributionDomainName:
    Description: "Domain name of the CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDistributionDomainName"
  CloudFrontDistributionId:
    Description: "ID of the CloudFront distribution"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDistributionId"
  S3BucketName:
    Description: "Name of the S3 bucket for static website content"
    Value: !Ref StaticWebsiteBucket
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName"