---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Empty AWS End User Messaging Infrastructure Template (Placeholder for future configuration)'

# This template is intentionally empty as per requirements to remove all messaging infrastructure
# It will be configured in the future

Resources:
  # No resources defined

Outputs:
  # No outputs defined